### ISSUE TITLE
Crash in iOS 16 beta 6

### ISSUE THREAD

**Issue by egpall** [creepymonster/GlucoseDirect#354] opened 2022-08-16 14:14 UTC
I'm back at 102, the following ones crash. 102 has no download from the database.

**Comment by creepymonster** [comment] 2022-08-21 14:12
Sorry for my late reply, I was on vacation and traveling with the RV for the last 14 days.

Unfortunately, there are issues with the ActivityKit (which is responsible for displaying the real-time glucose updates on the lockscreen) on iOS 16 Beta 6. I have disabled ActivityKit for now until a workaround is known or the issue is fixed with a future beta.

**Closed by creepymonster** 2022-08-21 14:12 UTC

**Comment by egpall** [comment] 2022-08-21 14:14
Thank you and I hope the vacation has been great!!!!

**Comment by creepymonster** [comment] 2022-08-21 14:18
Oh yes, thank you very much - we had a lot of fun - my first trip to Denmark was very nice :)

The version 1.0.0 (116) fixes the problem for now.

I hope that the display of current values via the ActivityKit will soon be possible again. Until then, I had (at least for now) only the possibility to disable the function :(

**Comment by egpall** [comment] 2022-08-21 14:20
I've already updated it and it's perfect!!!!! Thanks a lot

**Comment by egpall** [comment] 2022-08-21 14:30
I love the data, I export the database, extract Date, Time and Value, correct the time offset and paste everything into a spreadsheet. I am attaching capture.

**Comment by egpall** [comment] 2022-08-21 14:30
I love the data, I export the database, extract Date, Time and Value, correct the time offset and paste everything into a spreadsheet. I am attaching capture.
![Uploading 3A64FFC2-EA22-4862-97EB-71F6A8D58496.png…]()

**Comment by egpall** [comment] 2022-08-21 14:31
![80F6F17D-964F-4313-B2E3-F5FFD3FD1500](https://user-images.githubusercontent.com/61494891/185796066-379b53c6-174e-4277-b935-3f737b57f9bb.png)

**Comment by creepymonster** [comment] 2022-08-24 05:55
I find the idea cool - I have to look at that for evaluations. So far I had used the SQLite DB mainly to quickly make a backup of the data to be able to test without data.

**Comment by egpall** [comment] 2022-08-24 06:03
I have no idea about programming, if I know what I want and what I like. With a few clicks I get an impressive amount of data. Your work is impressive.

**Comment by egpall** [comment] 2022-08-24 06:08
A question, for the calculation of HbA1C, what formula do you use? If you can give it, of course. Thank you for everything.

**Comment by creepymonster** [comment] 2022-08-24 15:03
I think the work is great - it doesn't even need a program to do it - I think the spreadsheet is just the ticket <3

I got the formula for the GMI from https://www.jaeb.org/gmi/

GMI(%) = 3.31 + 0.02392 x [mean glucose in mg/dL]
GMI(mmol/mol) = 12.71 + 4.70587 x [mean glucose in mmol/L]

**Comment by egpall** [comment] 2022-08-24 18:47
Thank you very much!!!!! I guess for a period of time having the average glucose you have the GMI.

**Comment by creepymonster** [comment] 2022-08-24 20:25
I also find the mean value together with the standard deviation very good. Both values give a quick overview of where you stand.

The standard deviation provides information about how much the values fluctuate around the mean.

Unfortunately, the GMI does not take such fluctuations into account. The two values 40 and 240 result in a good GMI - but via mean value and standard deviation you can see that the mean value is not so good.

**Comment by creepymonster** [comment] 2022-08-24 20:27
The lower the standard deviation, the less fluctuation in blood glucose levels - this is a value where you can easily say "the lower the better".

**Comment by egpall** [comment] 2022-08-25 07:03
Thank you for all your attention

**Comment by w-aurelien** [comment] 2022-10-02 12:17
Hello

I'm trying to compile myself, but I have too ActivityKit problem.

<img width="1152" alt="Capture d’écran 2022-10-02 à 14 14 33" src="https://user-images.githubusercontent.com/100843604/193453456-9f829d1e-5845-4de2-949c-a29762a823b1.png">

I use Xcode 14.0.1 and iOs 16.0.2.

Any solutions ?

**Comment by creepymonster** [comment] 2022-10-02 19:22
There were several Xcode versions with 16.0 where the ActivityKit (for real-time glucose widgets on the lockscreen) was not available. The 14.0.1 release unfortunately does not include the ActivityKit.

For example, you can use the Xcode 14.1 beta 3 release to compile the app for iOS 15 and 16.0 as well. With the beta of 16.1 you can also test the realtime lockscreen widgets.

![62153B0D-E80C-4950-8979-6A9624F7239D](https://user-images.githubusercontent.com/5388815/193472359-21ce289e-1481-4570-ad22-7625f7195fe6.png)
